# Generated by Django 5.2.5 on 2025-09-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VardiyaCizelgesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ay', models.IntegerField()),
                ('yil', models.IntegerField()),
                ('veri', models.JSONField()),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('ay', 'yil')},
            },
        ),
    ]
