# Generated by Django 5.2.5 on 2025-09-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AracTakip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaka', models.CharField(max_length=50)),
                ('personel', models.CharField(max_length=100)),
                ('durum', models.CharField(max_length=20)),
                ('zaman', models.DateTimeField(auto_now_add=True)),
                ('yorum', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
