# Generated by Django 5.2.5 on 2025-09-02 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aractakip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('plaka', models.CharField(max_length=20, unique=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aractakip',
            name='plaka',
        ),
        migrations.AddField(
            model_name='aractakip',
            name='arac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='takipler', to='main.arac'),
        ),
    ]
