# Generated by Django 5.2.5 on 2025-09-02 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_arac_remove_aractakip_plaka_aractakip_arac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aractakip',
            name='arac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takipler', to='main.arac'),
        ),
    ]
